spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${LOGIN_URL:http://localhost:7080}/auth/realms/shoesclick-site
          jwk-set-uri: ${LOGIN_URL:http://localhost:7080}/auth/realms/shoesclick-site/protocol/openid-connect/certs

backend:
  services:
    customerUrl: ${API_CUSTOMER_URL:http://localhost:5000}/api--customer/
    productUrl: ${API_PRODUCT_URL:http://localhost:5000}/api--product/
    orderUrl: ${API_ORDER_URL:http://localhost:5000}/api--order/

cache:
  redis:
    host: ${CACHE_URL:localhost}
    port: 6379
    ttlCache: 3