spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${LOGIN_HOST:http://svc-login.ns-login.svc.cluster.local:7080}/auth/realms/shoesclick-site
          jwk-set-uri: ${LOGIN_HOST:http://svc-login.ns-login.svc.cluster.local:7080}/auth/realms/shoesclick-site/protocol/openid-connect/certs

backend:
  services:
    customerUrl: http://localhost:5000/api--customer/
    productUrl: http://localhost:5100/api--product/
    orderUrl: http://localhost:5300/api--order/

cache:
  redis:
    host: redis.ns-infra.svc.cluster.local
    port: 6379
    ttlCache: 3