spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://svc-login.ns-login.svc.cluster.local:7080/auth/realms/shoesclick-site
          jwk-set-uri: http://svc-login.ns-login.svc.cluster.local:7080/auth/realms/shoesclick-site/protocol/openid-connect/certs

backend:
  services:
    customerUrl: http://svc-api--customer.shoes-eks.svc.cluster.local:5000/api--customer/
    productUrl: http://svc-api--product.shoes-eks.svc.cluster.local:5000/api--product/
    orderUrl: http://svc-api--order.shoes-eks.svc.cluster.local:5000/api--order/

cache:
  redis:
    host: redis.ns-infra.svc.cluster.local
    port: 6379
    ttlCache: 3


eureka:
  client:
    serviceUrl:
      defaultZone: http://svc-server--discovery-stack.shoes-eks.svc.cluster.local:8762/eureka/
  instance:
    prefer-ip-address: 'true'

otel:
  traces:
    exporter: jaeger
  exporter:
    jaeger:
      endpoint: http://jaeger-collector.monitoracao.svc.cluster.local:14268/api/traces
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"