spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://login.shoesclick.local:7080/auth/realms/shoesclick-site
          jwk-set-uri: http://login.shoesclick.local:7080/auth/realms/shoesclick-site/protocol/openid-connect/certs

backend:
  services:
    customerUrl: http://api-customer.shoesclick.local:5000/api--customer/
    productUrl: http://api-product.shoesclick.local:5000/api--product/
    orderUrl: http://api-order.shoesclick.local:5000/api--order/

cache:
  redis:
    host: redis.shoesclick.local
    port: 6379
    ttlCache: 3