spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/auth/realms/shoesclick-site
          jwk-set-uri: http://localhost:7080/auth/realms/shoesclick-site/protocol/openid-connect/certs

backend:
  services:
    customerUrl: http://localhost:5000/api--customer/
    productUrl: http://localhost:5000/api--product/
    orderUrl: http://localhost:5000/api--order/

cache:
  redis:
    host: localhost
    port: 6379
    ttlCache: 3


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: 'true'

management:
  tracing:
    baggage:
      enabled: 'true'
    propagation:
      type: 'w3c '
    enabled: 'true'
  zipkin:
    tracing:
      endpoint: 'http://localhost:9411/api/v2/spans'
