spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE:America/Sao_Paulo}
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    tomcat:
      max-active: ${SPRING_DATASOURCE_MAX_ACTIVE:10}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/dborder?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${LOGIN_URL:http://localhost:7080}/auth/realms/shoesclick-site
          jwk-set-uri: ${LOGIN_URL:http://localhost:7080}/auth/realms/shoesclick-site/protocol/openid-connect/certs

kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost}:9092
  schemaRegistry: http://${SCHEMA_REGISTRY_HOST:localhost}:8081
  notification:
    topic: kfk-order-notification
    groupId: grp-order-notification
  payment:
    topic: kfk-order-payment
    groupId: grp-order-payment

backend:
  services:
    customerUrl: ${API_CUSTOMER_URL:http://localhost:5000}/api--customer/
    productUrl: ${API_PRODUCT_URL:http://localhost:5000}/api--product