spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE:America/Sao_Paulo}
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    tomcat:
      max-active: ${SPRING_DATASOURCE_MAX_ACTIVE:10}
    url: jdbc:mysql://mysql.ns-infra.svc.cluster.local:3306/dborder?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://login.ns-infra.svc.cluster.local:7080/auth/realms/shoesclick-site
          jwk-set-uri: http://login.ns-infra.svc.cluster.local:7080/auth/realms/shoesclick-site/protocol/openid-connect/certs

kafka:
  bootstrap-servers: kafka.ns-infra.svc.cluster.local:9092
  schemaRegistry: http://schema-registry.ns-infra.svc.cluster.local:8081
  notification:
    topic: kfk-order-notification
    groupId: grp-order-notification
  payment:
    topic: kfk-order-payment
    groupId: grp-order-payment

backend:
  services:
    customerUrl: http://api--customer.shoes-eks.svc.cluster.local:5000/api--customer/
    productUrl: http://api--product.shoes-eks.svc.cluster.local:5000/api--product/


eureka:
  client:
    serviceUrl:
      defaultZone: http://svc-server--discovery-stack.shoes-eks.svc.cluster.local:8762/eureka/
  instance:
    prefer-ip-address: 'true'