spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE:America/Sao_Paulo}
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    tomcat:
      max-active: ${SPRING_DATASOURCE_MAX_ACTIVE:10}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/dbnotification?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
  rabbitmq:
    username: "admin"
    password: "passw123"
    port: 5672
    host: localhost
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    username: ${EMAIL_USERNAME:clayton.oliveira@al.infnet.edu.br}
    host: ${SMTP_HOST:smtp.gmail.com}
    password: { EMAIL_PASSWORD:cccc }
    port: '587'

rabbitmq:
  exchange: shoesclick_exchange
  notification:
    queue: mq_notification
    routingKey: notification_routingkey

backend:
  services:
    customerUrl: http://localhost:8081/api--customer/
    productUrl: http://localhost:8082/api--product